// pub mod acronym;
pub mod allergies;
// pub mod anagrams;
// pub mod armstrong_number;
// pub mod buffer;
// pub mod clock;
// pub mod gigasecond;
// pub mod lasagna;
// pub mod luhn_checksum;
// pub mod macros;
// pub mod magazine;
// pub mod minesweeper;
// pub mod parallel_letter_frequency;
// pub mod poker;
// pub mod reverse_string;
// pub mod rpn;
// pub mod space_age;
// pub mod sublist;
